---

- name: Add php package repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes
  become: true

- name: Install php
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php8.1
    - libapache2-mod-php8.1
    - php8.1-common
    - php8.1-xml
    - php8.1-curl
    - php8.1-cli
    - php8.1-pgsql
    - php8.1-gd
    - php8.1-opcache
    - php8.1-mbstring
    - php8.1-tokenizer
    - php8.1-bcmath
    - php8.1-zip
    - unzip
  become: true

- name: Configure php
  ansible.builtin.lineinfile:
    path: /etc/php/8.1/apache2/php.ini
    state: present
    regexp: '^;cgi.fix_pathinfo=1'
    line: 'cgi.fix_pathinfo=0'
  become: true
  notify: Reload apache
