---

- name: Start apache
  ansible.builtin.service:
    name: apache2
    state: started
  become: true

- name: Reload apache
  ansible.builtin.service:
    name: apache2
    state: reloaded
  become: true
