---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yaml

  tasks:
    - block:
      - include_tasks: tasks/clone_repo.yaml
      - include_tasks: tasks/permissions.yaml
      - include_tasks: tasks/check_cache.yaml
      - include_tasks: tasks/composer.yaml
      - include_tasks: tasks/env.yaml
      - include_tasks: tasks/app_optimization.yaml
      - include_tasks: tasks/database.yaml
      - include_tasks: tasks/notify_restart_apache.yaml
