---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yaml

  tasks:
    - block:
      - include_tasks: tasks/clone_repo.yml
      - include_tasks: tasks/permissions.yml
      - include_tasks: tasks/check_cache.yml
      - include_tasks: tasks/composer.yml
      - include_tasks: tasks/env.yaml
      - include_tasks: tasks/app_optimization.yml
      - include_tasks: tasks/database.yml
      - include_tasks: tasks/notify_restart_apache.yml
